use egui::Key;
use smithay_client_toolkit::seat::keyboard::Keysym;

pub(crate) fn wl_to_egui(keysym: Keysym) -> Option<Key> {
    Some(match keysym {
        Keysym::Down | Keysym::KP_Down => Key::ArrowDown,
        Keysym::Left | Keysym::KP_Left => Key::ArrowLeft,
        Keysym::Right | Keysym::KP_Right => Key::ArrowRight,
        Keysym::Up | Keysym::KP_Up => Key::ArrowUp,

        Keysym::Escape => Key::Escape,
        Keysym::Tab => Key::Tab,
        Keysym::BackSpace => Key::Backspace,
        Keysym::Return | Keysym::KP_Enter => Key::Enter,

        Keysym::Help | Keysym::Insert | Keysym::KP_Insert => Key::Insert,
        Keysym::Delete => Key::Delete,
        Keysym::Home | Keysym::KP_Home => Key::Home,
        Keysym::End | Keysym::KP_End => Key::End,
        Keysym::Page_Up | Keysym::KP_Page_Up => Key::PageUp,
        Keysym::Page_Down | Keysym::KP_Page_Down => Key::PageDown,

        Keysym::XF86_Copy => Key::Copy,
        Keysym::XF86_Cut => Key::Cut,
        Keysym::XF86_Paste => Key::Paste,

        Keysym::space | Keysym::KP_Space => Key::Space,
        Keysym::colon => Key::Colon,
        Keysym::comma => Key::Comma,
        Keysym::minus => Key::Minus,
        Keysym::period => Key::Period,
        Keysym::plus => Key::Plus,
        Keysym::equal | Keysym::KP_Equal => Key::Equals,
        Keysym::semicolon => Key::Semicolon,
        Keysym::backslash => Key::Backslash,
        Keysym::slash => Key::Slash,
        Keysym::vertbar => Key::Pipe,
        Keysym::question => Key::Questionmark,
        Keysym::exclam => Key::Exclamationmark,
        Keysym::bracketleft => Key::OpenBracket,
        Keysym::bracketright => Key::CloseBracket,
        Keysym::braceleft => Key::OpenCurlyBracket,
        Keysym::braceright => Key::CloseCurlyBracket,
        Keysym::grave => Key::Backtick,
        Keysym::apostrophe => Key::Quote,

        Keysym::_0 | Keysym::KP_0 => Key::Num0,
        Keysym::_1 | Keysym::KP_1 => Key::Num1,
        Keysym::_2 | Keysym::KP_2 => Key::Num2,
        Keysym::_3 | Keysym::KP_3 => Key::Num3,
        Keysym::_4 | Keysym::KP_4 => Key::Num4,
        Keysym::_5 | Keysym::KP_5 => Key::Num5,
        Keysym::_6 | Keysym::KP_6 => Key::Num6,
        Keysym::_7 | Keysym::KP_7 => Key::Num7,
        Keysym::_8 | Keysym::KP_8 => Key::Num8,
        Keysym::_9 | Keysym::KP_9 => Key::Num9,

        Keysym::A => Key::A,
        Keysym::B => Key::B,
        Keysym::C => Key::C,
        Keysym::D => Key::D,
        Keysym::E => Key::E,
        Keysym::F => Key::F,
        Keysym::G => Key::G,
        Keysym::H => Key::H,
        Keysym::I => Key::I,
        Keysym::J => Key::J,
        Keysym::K => Key::K,
        Keysym::L => Key::L,
        Keysym::M => Key::M,
        Keysym::N => Key::N,
        Keysym::O => Key::O,
        Keysym::P => Key::P,
        Keysym::Q => Key::Q,
        Keysym::R => Key::R,
        Keysym::S => Key::S,
        Keysym::T => Key::T,
        Keysym::U => Key::U,
        Keysym::V => Key::V,
        Keysym::W => Key::W,
        Keysym::X => Key::X,
        Keysym::Y => Key::Y,
        Keysym::Z => Key::Z,

        Keysym::F1 => Key::F1,
        Keysym::F2 => Key::F2,
        Keysym::F3 => Key::F3,
        Keysym::F4 => Key::F4,
        Keysym::F5 => Key::F5,
        Keysym::F6 => Key::F6,
        Keysym::F7 => Key::F7,
        Keysym::F8 => Key::F8,
        Keysym::F9 => Key::F9,
        Keysym::F10 => Key::F10,
        Keysym::F11 => Key::F11,
        Keysym::F12 => Key::F12,
        Keysym::F13 => Key::F13,
        Keysym::F14 => Key::F14,
        Keysym::F15 => Key::F15,
        Keysym::F16 => Key::F16,
        Keysym::F17 => Key::F17,
        Keysym::F18 => Key::F18,
        Keysym::F19 => Key::F19,
        Keysym::F20 => Key::F20,
        Keysym::F21 => Key::F21,
        Keysym::F22 => Key::F22,
        Keysym::F23 => Key::F23,
        Keysym::F24 => Key::F24,
        Keysym::F25 => Key::F25,
        Keysym::F26 => Key::F26,
        Keysym::F27 => Key::F27,
        Keysym::F28 => Key::F28,
        Keysym::F29 => Key::F29,
        Keysym::F30 => Key::F30,
        Keysym::F31 => Key::F31,
        Keysym::F32 => Key::F32,
        Keysym::F33 => Key::F33,
        Keysym::F34 => Key::F34,
        Keysym::F35 => Key::F35,

        _ => return None,
    })
}
